name: intl_phone_number_input
description: A simple and customizable flutter package on International Phone Number Input.
version: 1.0.1
author: Ogunye Nathaniel Oluwatobiloba <oluwatobilobaogunye@gmail.com>
homepage: https://github.com/natintosh/intl-phone-number-input

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  libphonenumber: ^2.0.0


dev_dependencies:
  test: ^1.16.8
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/flags/
    - packages/intl_phone_number_input/src/models/countries.json
